apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: keyval
spec:
  nodes: 1
  volumePermissions: true
  prometheus: false
  tls: true
  certIssuer: selfsigned
  prometheusLabels:
    prometheus: "1"
