apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: valkey-operator.v0.0.53
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Valkey is the Schema for the valkeys API
      displayName: Valkey
      kind: Valkey
      name: valkeys.hyperspike.io
      version: v1
  description: This operator creates valkey clusters and makes them available to other
    services on the k8s cluster
  displayName: valkey-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - valkey
  - redis
  - database
  links:
  - name: Valkey Operator
    url: https://valkey-operator.domain
  maturity: alpha
  provider:
    name: hyperspike
    url: https://hyperspike.io/
  version: 0.0.53
