name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'release-*'
      - 'master'
      - 'main'
    tags:
      - 'v*'
      - '!pkg*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag'
    steps:
    - run: |
        gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --generate-notes -R $GITHUB_REPOSITORY
      env:
        GH_TOKEN: ${{ github.token }}
