name: release
on:
  release:
    types:
    - created

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    name: Upload release assets
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true
      - name: Build Installer
        run: make build-installer IMG=ghcr.io/hyperspike/valkey-operator:${{ github.ref_name }}
      - name: Upload dist/install.yaml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/install.yaml
          asset_name: install.yaml
          tag: ${{ github.ref }}
          overwrite: true
